artifacts:
  - path: build\artifacts\*.update
    name: Sitecore.Akamai
before_build:
  - nuget sources add -Name SitecorePublicFeed -Source https://sitecore.myget.org/F/sc-packages/api/v3/index.json
  - nuget restore Sitecore.Akamai.sln
build:
  project: Sitecore.Akamai.sln
after_build:
  - ps: .\build\build.ps1  
deploy:
  release: Sitecore.Akamai-v$(appveyor_build_version)
  description: 'Using Akamai features inside Sitecore'
  provider: GitHub
  auth_token:
    secure: rkLSxUbN2YMMG/r6lzLq1PN0n07dqJBtk/8ZR2c/InGy0SBOsmqGXfIQWMQOZUAs 
  draft: false
  prerelease: false
  on:
    branch: master                # release from master branch only
    appveyor_repo_tag: true       # deploy on tag push only
install:
  - ps: Install-Module -Name Sitecore.Courier -Force
  - ps: Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  - choco install sitecore-courier
